// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ATest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void login() {
    // Test name: login
    // Step # | name | target | value
    // 1 | open | https://console.saytutension.sante.sn/home/community-health-worker | 
    driver.get("https://console.saytutension.sante.sn/home/community-health-worker");
    // 2 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 3 | type | id=email | admin@localhost.com
    driver.findElement(By.id("email")).sendKeys("admin@localhost.com");
    // 4 | type | id=password | &3.Bd)d&6D&Y7?p&G|
    driver.findElement(By.id("password")).sendKeys("&3.Bd)d&6D&Y7?p&G|");
    // 5 | click | css=.bg-primary-saytu | 
    driver.findElement(By.cssSelector(".bg-primary-saytu")).click();
    // 6 | click | css=.btn-primary | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
  }
}
